version: '3.8'

services:
  # Qdrant向量数据库
  qdrant:
    image: qdrant/qdrant
    container_name: dwp-qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - dwp-network

   # ---------- Java 后端 ----------
  java-backend:
    build:
      context: .
      dockerfile: Dockerfile.java
    container_name: dwp-java-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dwp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=utf8
      PYTHON_RAG_SERVICE_URL: http://python-rag:8002
      # ← 新增：推荐服务 URL（在代码里用 System.getenv("RECOMMENDER_URL") 读取）
      RECOMMENDER_URL: http://paper-recommender:8000
    depends_on:
      - paper-recommender
    networks:
      - dwp-network


  # Python RAG服务
  python-rag:
    build:
      context: ./python-rag-service
      dockerfile: Dockerfile
    container_name: dwp-python-rag
    ports:
      - "8002:8002"
    environment:
      JAVA_BACKEND_URL: http://java-backend:8080
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
    depends_on:
      - qdrant
      - java-backend
    networks:
      - dwp-network

 # ---------------- 用户行为推荐（Paper Recommender） ----------------
  paper-recommender:
    build:
      context: ./paper-recommendation-service        # ← 你的 paper‑recommendation-service 目录
      dockerfile: Dockerfile
    container_name: dwp-paper-recommender
    ports:
      - "8010:8000"      # 开发期暴露；线上内部即可
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: 123123LSH
      DB_NAME: dwp
      MODEL_NAME: allenai-specter         # 或 all-MiniLM-L6-v2
    volumes:
      - recommender_cache:/root/.cache/huggingface
      - recommender_data:/app                      # 存 faiss.index / *.npy
    depends_on: [ ]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 5s
      retries: 5
    networks: [ dwp-network ]


 # ---------- Nginx 反向代理 ----------
  nginx:
    image: nginx:alpine
    container_name: dwp-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - java-backend
      - python-rag
      - paper-recommender
    networks:
      - dwp-network

# ---------- 数据卷 ----------
volumes:
  mysql_data:
  qdrant_data:
  recommender_cache:     # HugginFace 权重缓存 (≈500 MB)
  recommender_data:      # faiss.index & embeddings.npy

# ---------- 网络 ----------
networks:
  dwp-network:
    driver: bridge